version: "2"
services:
  orders-api:
    build: ./api/orders
    ports:
      - "8082:8082"
  products-api:
    build: ./api/products
    ports:
      - "8083:8083"
  consul1:
    image: "progrium/consul:latest"
    container_name: "consul1"
    hostname: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-server -bootstrap-expect 3 -ui-dir /ui"
  consul2:
    image: "progrium/consul:latest"
    container_name: "consul2"
    hostname: "consul2"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "-server -join consul1"
    depends_on:
      - consul1
  consul3:
    image: "progrium/consul:latest"
    container_name: "consul3"
    hostname: "consul3"
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "-server -join consul1"
    depends_on:
      - consul1
  fabio:
    image: magiconair/fabio:latest
    volumes:
      - ./fabio:/etc/fabio:ro
    links:
      - consul1
    ports:
      - "9998:9998" # GUI/management
      - "9999:9999" # HTTP exposed